spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888  # Your config server
#      uri: http://config-server:8888


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
#      defaultZone: http://discovery-server:8761/eureka
      defaultZone: http://localhost:8761/eureka
