spring.application.name=product-service
logging.level.root=ERROR
# MinIO Configuration
minio.url=http://localhost:9000
minio.access.name=minio
minio.access.secret=minio123
minio.bucket-name=springcommerce
