server:
  port: 8083

# Do not register with Eureka
eureka:
  client:
    enabled: false

# Disable config client
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5431/cartdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true